### ISSUE TITLE
Mejorar los iconos de las Categorias

### ISSUE THREAD

**Issue by hminaya** [hminaya/DevDomSocialAppAndroid#2]
Pueden encontrar los iconos actuales en el API (http://js.developers.do/js/devdom.js), la idea es reemplazar esas imagenes por otras que se vean mejor :)....

**Comment by jeancventura** [comment]
De donde se pueden sacar las imagenes? Se propondrian por aqui y ustedes la aprueban?

**Comment by hminaya** [comment]
Si son las de las categorias puedes simplemente colocar los links aqui de las nuevas imagenes, ya que las mismas vienen de un JSON y estan en un webserver fuera de la app. Deben ser en PNG, transparentes y del mismo tamaño.

**Comment by hminaya** [comment]
fixed.
